version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - lll
    - funlen
    - gocognit
    - gocyclo
    - importas
  settings:
    funlen:
      lines: 60
      statements: -1
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
      tab-width: 4
    staticcheck:
      checks:
        - all
        - '-ST1000'
        - '-ST1003'
        - '-ST1020'
        - '-ST1021'
        - '-ST1023'
        - '-QF1003'
        - '-QF1004'
        - '-QF1008'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - lll
        path: _test.go$
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$