// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/dictionary/{word}": {
            "get": {
                "description": "Get dictionary definition and pronunciation for a given word from Cambridge Dictionary API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dictionary"
                ],
                "summary": "Search dictionary for word definition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Word to search for",
                        "name": "word",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dictionary definition found successfully",
                        "schema": {
                            "$ref": "#/definitions/models.DictionaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid URL format or missing word parameter",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Word not found, API error, or JSON encoding failure",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Returns server status to verify the service is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Server is healthy",
                        "schema": {
                            "$ref": "#/definitions/models.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/questions": {
            "get": {
                "description": "Get all questions, supports pagination through query parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of records to return (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of Questions retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Question"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new question entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "description": "Question data to create",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Question"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Question created successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Question"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to insert data into database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/count": {
            "get": {
                "description": "Get the total count of questions in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "responses": {
                    "200": {
                        "description": "Total count of questions",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to count questions in database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/definition/{id}": {
            "delete": {
                "description": "Delete a specific question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Question deleted successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid definition ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to delete data from database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/random": {
            "post": {
                "description": "Randomly obtain the required number of questions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "description": "Random filter criteria including count and optional filter",
                        "name": "randomFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QuestionRandomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Random questions retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Question"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body or count parameter",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/{id}": {
            "get": {
                "description": "Get the question by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "A question retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Question"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing question's properties like familiarity level",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question data to update",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Question"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Question updated successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Question"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid question ID or request body",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to update data in database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words": {
            "get": {
                "description": "Get all words with their definitions and pronunciation information, supports pagination through query parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of records to return (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of words retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Word"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new word entry in the dictionary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "description": "Word data to create",
                        "name": "word",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Word created successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to insert data into database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/count": {
            "post": {
                "description": "Count the number of words that match the specified filter criteria across both words and word_definitions tables",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "description": "Search filter criteria",
                        "name": "searchFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SearchFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Count of words matching the filter criteria",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body or filter",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/definition/{id}": {
            "put": {
                "description": "Update an existing word definition's content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Definition data to update",
                        "name": "definition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.WordDefinition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Word definition updated successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid definition ID or request body",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to update data in database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new definition to an existing word",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Word definition data",
                        "name": "definition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.WordDefinition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Word definition created successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid word ID or request body",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to insert data into database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a specific word definition",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Word definition deleted successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid definition ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to delete data from database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/random": {
            "post": {
                "description": "Get random words using specified filter criteria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "description": "Random filter criteria including count and optional filter",
                        "name": "randomFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RandomFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Random words retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Word"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body or count parameter",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/search": {
            "post": {
                "description": "Search for words using specified filter criteria across both words and word_definitions tables. Supports equal, not equal, in, and not in operations with pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "description": "Search filter criteria",
                        "name": "searchFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SearchFilter"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of records to return (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Words found matching the search criteria",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Word"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body, filter, or query parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/{id}": {
            "put": {
                "description": "Update an existing word's properties like familiarity level",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Word data to update",
                        "name": "word",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Word updated successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid word ID or request body",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to update data in database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a word and all its associated definitions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Word deleted successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid word ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to delete data from database",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DefinitionInfo": {
            "type": "object",
            "properties": {
                "definition": {
                    "type": "string"
                },
                "example": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.DictionaryResponse": {
            "type": "object",
            "properties": {
                "meanings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MeaningInfo"
                    }
                },
                "phonetics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PhoneticInfo"
                    }
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "models.MeaningInfo": {
            "type": "object",
            "properties": {
                "definitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DefinitionInfo"
                    }
                },
                "partOfSpeech": {
                    "type": "string"
                }
            }
        },
        "models.PhoneticInfo": {
            "type": "object",
            "properties": {
                "audio": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                }
            }
        },
        "models.QuestionRandomRequest": {
            "type": "object",
            "required": [
                "count"
            ],
            "properties": {
                "count": {
                    "type": "integer",
                    "maximum": 1000,
                    "minimum": 1
                }
            }
        },
        "models.RandomFilter": {
            "type": "object",
            "required": [
                "count"
            ],
            "properties": {
                "count": {
                    "type": "integer",
                    "maximum": 1000,
                    "minimum": 1
                },
                "filter": {
                    "$ref": "#/definitions/models.SearchFilter"
                }
            }
        },
        "models.SearchCondition": {
            "type": "object",
            "required": [
                "key",
                "operator",
                "value"
            ],
            "properties": {
                "key": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.SearchFilter": {
            "type": "object",
            "required": [
                "conditions",
                "logic"
            ],
            "properties": {
                "conditions": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/models.SearchCondition"
                    }
                },
                "logic": {
                    "description": "\"AND\" or \"OR\"",
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.Question": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "count_failure_practise": {
                    "type": "integer"
                },
                "count_practise": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "option_a": {
                    "type": "string"
                },
                "option_b": {
                    "type": "string"
                },
                "option_c": {
                    "type": "string"
                },
                "option_d": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.Word": {
            "type": "object",
            "properties": {
                "definitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word-flashcard_internal_models.WordDefinition"
                    }
                },
                "familiarity": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "word": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.WordDefinition": {
            "type": "object",
            "properties": {
                "definition": {
                    "type": "string"
                },
                "examples": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "part_of_speech": {
                    "type": "string"
                },
                "phonetics": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Word Flashcard API",
	Description:      "Flashcards help you learn more vocabulary anytime, anywhere.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
