// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/dictionary/{word}": {
            "get": {
                "description": "Get dictionary definition and pronunciation for a given word from Cambridge Dictionary API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dictionary"
                ],
                "summary": "Search dictionary for word definition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Word to search for",
                        "name": "word",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dictionary definition found successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.DictionaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - Missing word parameter",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Word not found in the dictionary",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad gateway - Dictionary service unavailable",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Returns server status to verify the service is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Server is healthy",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/information": {
            "get": {
                "description": "Returns application version read from the root VERSION file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Application information endpoint",
                "responses": {
                    "200": {
                        "description": "Application information",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.InformationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - VERSION file not found or unreadable",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/notes": {
            "get": {
                "description": "Get all notes, supports pagination and multi-column sorting through query parameters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of records to return (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort columns/expressions, comma-separated. Allowed: id,title,sort_order,created_at,updated_at",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of notes retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Note"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new note card entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "parameters": [
                    {
                        "description": "Note data to create",
                        "name": "note",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Note"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Note created successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Note"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict - A note with this title already exists",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to insert data into database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/notes/count": {
            "get": {
                "description": "Get the total count of notes in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "responses": {
                    "200": {
                        "description": "Total count of notes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to count notes in database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/notes/search": {
            "post": {
                "description": "Search for notes using specified filter criteria. Supports equal, not equal, in, not in, like and other operations with pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "parameters": [
                    {
                        "description": "Search filter criteria",
                        "name": "searchFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.SearchFilter"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of records to return (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort columns/expressions, comma-separated. Allowed: id,title,sort_order,created_at,updated_at",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Notes found matching the search criteria",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Note"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body, filter, or query parameters",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/notes/{id}": {
            "get": {
                "description": "Get a specific note by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Note ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Note retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Note"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid note ID",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Note not found",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing note's properties",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Note ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Note data to update",
                        "name": "note",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Note"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Note updated successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Note"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid note ID or request body",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Note not found",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict - A note with this title already exists",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to update data in database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a specific note",
                "tags": [
                    "notes"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Note ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Note deleted successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid note ID",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Note not found",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to delete data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions": {
            "get": {
                "description": "Get all questions, supports pagination and multi-column sorting through query parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of records to return (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort columns/expressions, comma-separated. Format: col,-col,(expr),-(expr). Allowed: id,question,answer,count_practise,count_failure_practise,created_at,updated_at",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of Questions retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Question"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new question entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "description": "Question data to create",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Question"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Question created successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Question"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to insert data into database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/count": {
            "get": {
                "description": "Get the total count of questions in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "responses": {
                    "200": {
                        "description": "Total count of questions",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to count questions in database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/random": {
            "post": {
                "description": "Randomly obtain the required number of questions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "description": "Random filter criteria including count and optional filter",
                        "name": "randomFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.QuestionRandomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Random questions retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Question"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body or count parameter",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/stats": {
            "get": {
                "description": "Get question count distribution by accuracy rate in 10% intervals, each bucket further broken down by practice count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "responses": {
                    "200": {
                        "description": "Question accuracy distribution",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.QuestionStats"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch questions",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/trend": {
            "get": {
                "description": "Get daily practice count / accuracy rate across all questions over the last N days, zero-filled for days with no activity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of days to include (default: 30, max: 90)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Daily trend points, ascending by date",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.QuestionTrendPoint"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid days parameter",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/{id}": {
            "get": {
                "description": "Get the question by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "A question retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Question"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Question not found",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing question's properties like familiarity level",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question data to update",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Question"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Question updated successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Question"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid question ID or request body",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Question not found",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to update data in database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a specific question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Question deleted successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid question ID",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Question not found",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to delete data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/{id}/logs": {
            "get": {
                "description": "Get the most recent answer log entries for a question, most recent first",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of entries to return (default: 15, max: 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Recent answer log entries",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.QuestionAnswerLogEntry"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid question ID or limit parameter",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words": {
            "get": {
                "description": "Get all words with their definitions and pronunciation information, supports pagination through query parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of records to return (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of words retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Word"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new word entry in the dictionary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "description": "Word data to create",
                        "name": "word",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Word created successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict - A word with this text already exists",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to insert data into database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/count": {
            "post": {
                "description": "Count the number of words that match the specified filter criteria across both words and word_definitions tables",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "description": "Search filter criteria",
                        "name": "searchFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.SearchFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Count of words matching the filter criteria",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body or filter",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/definition/{id}": {
            "put": {
                "description": "Update an existing word definition's content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Definition data to update",
                        "name": "definition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.WordDefinition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Word definition updated successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid definition ID or request body",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Word definition not found",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to update data in database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new definition to an existing word",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Word definition data",
                        "name": "definition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.WordDefinition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Word definition created successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid word ID or request body",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to insert data into database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a specific word definition",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Word definition deleted successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid definition ID",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Word definition not found",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to delete data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/random": {
            "post": {
                "description": "Get random words for a quiz, weighted by familiarity ratio (familiarity_levels) or exact quota (per_category_counts); prioritizes never-practiced then longest-idle words",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "description": "Random request criteria including count and either familiarity_levels or per_category_counts",
                        "name": "randomRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.WordRandomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Random words retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Word"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body or count parameter",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/search": {
            "post": {
                "description": "Search for words using specified filter criteria across both words and word_definitions tables. Supports equal, not equal, in, and not in operations with pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "description": "Search filter criteria",
                        "name": "searchFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.SearchFilter"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of records to return (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort columns, comma-separated. Format: col,-col. Allowed: id,word,familiarity,count_practise,created_at",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Words found matching the search criteria",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.Word"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid request body, filter, or query parameters",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/stats": {
            "get": {
                "description": "Get word count distribution by familiarity level and practice count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "responses": {
                    "200": {
                        "description": "Word familiarity distribution",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.WordStats"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to count words",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/trend": {
            "get": {
                "description": "Get daily practice count / improvement rate / average familiarity score across all words over the last N days, zero-filled for days with no activity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of days to include (default: 30, max: 90)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Daily trend points, ascending by date",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.WordTrendPoint"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid days parameter",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/{id}": {
            "put": {
                "description": "Update an existing word's properties like familiarity level",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Word data to update",
                        "name": "word",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Word updated successfully",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.Word"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid word ID or request body",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Word not found",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict - A word with this text already exists",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to update data in database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a word and all its associated definitions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Word deleted successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid word ID",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - Word not found",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to delete data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/{id}/logs": {
            "get": {
                "description": "Get the most recent practice log entries for a word, most recent first",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Word ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of entries to return (default: 10, max: 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Recent practice log entries",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/word-flashcard_internal_models.WordPracticeLogEntry"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid word ID or limit parameter",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - Failed to fetch data from database",
                        "schema": {
                            "$ref": "#/definitions/word-flashcard_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "word-flashcard_internal_models.AccuracyBucket": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "practice_count_breakdown": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word-flashcard_internal_models.PracticeCountBucket"
                    }
                },
                "range": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.DefinitionInfo": {
            "type": "object",
            "properties": {
                "definition": {
                    "type": "string"
                },
                "example": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "word-flashcard_internal_models.DictionaryResponse": {
            "type": "object",
            "properties": {
                "meanings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word-flashcard_internal_models.MeaningInfo"
                    }
                },
                "phonetics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word-flashcard_internal_models.PhoneticInfo"
                    }
                }
            }
        },
        "word-flashcard_internal_models.ErrorCode": {
            "type": "string",
            "enum": [
                "invalid_request",
                "validation_error",
                "not_found",
                "conflict",
                "internal_error",
                "upstream_unavailable"
            ],
            "x-enum-varnames": [
                "ErrCodeInvalidRequest",
                "ErrCodeValidationError",
                "ErrCodeNotFound",
                "ErrCodeConflict",
                "ErrCodeInternalError",
                "ErrCodeUpstreamUnavailable"
            ]
        },
        "word-flashcard_internal_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/word-flashcard_internal_models.ErrorCode"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.InformationResponse": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.MeaningInfo": {
            "type": "object",
            "properties": {
                "definitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word-flashcard_internal_models.DefinitionInfo"
                    }
                },
                "partOfSpeech": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.Note": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "sort_order": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.PhoneticInfo": {
            "type": "object",
            "properties": {
                "audio": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.PracticeCountBucket": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "range": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.Question": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "count_failure_practise": {
                    "type": "integer"
                },
                "count_practise": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "option_a": {
                    "type": "string"
                },
                "option_b": {
                    "type": "string"
                },
                "option_c": {
                    "type": "string"
                },
                "option_d": {
                    "type": "string"
                },
                "practiced": {
                    "type": "boolean"
                },
                "question": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "selected_option": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.QuestionAnswerLogEntry": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_correct": {
                    "type": "boolean"
                },
                "selected_option": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.QuestionRandomRequest": {
            "type": "object",
            "required": [
                "count"
            ],
            "properties": {
                "count": {
                    "type": "integer",
                    "maximum": 1000,
                    "minimum": 1
                },
                "exclude_recent_days": {
                    "type": "integer"
                }
            }
        },
        "word-flashcard_internal_models.QuestionStats": {
            "type": "object",
            "properties": {
                "accuracy_distribution": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word-flashcard_internal_models.AccuracyBucket"
                    }
                }
            }
        },
        "word-flashcard_internal_models.QuestionTrendPoint": {
            "type": "object",
            "properties": {
                "accuracy_rate": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "practice_count": {
                    "type": "integer"
                }
            }
        },
        "word-flashcard_internal_models.SearchCondition": {
            "type": "object",
            "required": [
                "key",
                "operator"
            ],
            "properties": {
                "key": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.SearchFilter": {
            "type": "object",
            "required": [
                "conditions",
                "logic"
            ],
            "properties": {
                "conditions": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/word-flashcard_internal_models.SearchCondition"
                    }
                },
                "logic": {
                    "description": "\"AND\" or \"OR\"",
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.Word": {
            "type": "object",
            "properties": {
                "count_practise": {
                    "type": "integer"
                },
                "definitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word-flashcard_internal_models.WordDefinition"
                    }
                },
                "familiarity": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "increment_count_practise": {
                    "type": "boolean"
                },
                "reminder": {
                    "type": "string"
                },
                "word": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.WordDefinition": {
            "type": "object",
            "properties": {
                "definition": {
                    "type": "string"
                },
                "examples": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "part_of_speech": {
                    "type": "string"
                },
                "phonetics": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "word-flashcard_internal_models.WordFamiliarityDistribution": {
            "type": "object",
            "properties": {
                "green": {
                    "type": "integer"
                },
                "red": {
                    "type": "integer"
                },
                "yellow": {
                    "type": "integer"
                }
            }
        },
        "word-flashcard_internal_models.WordPracticeLogEntry": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "familiarity": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "previous_familiarity": {
                    "type": "string"
                }
            }
        },
        "word-flashcard_internal_models.WordRandomRequest": {
            "type": "object",
            "required": [
                "count"
            ],
            "properties": {
                "count": {
                    "type": "integer",
                    "maximum": 1000,
                    "minimum": 1
                },
                "familiarity_levels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "per_category_counts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        },
        "word-flashcard_internal_models.WordStats": {
            "type": "object",
            "properties": {
                "familiarity_distribution": {
                    "$ref": "#/definitions/word-flashcard_internal_models.WordFamiliarityDistribution"
                },
                "practice_count_distribution": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word-flashcard_internal_models.PracticeCountBucket"
                    }
                }
            }
        },
        "word-flashcard_internal_models.WordTrendPoint": {
            "type": "object",
            "properties": {
                "avg_familiarity_score": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "improvement_rate": {
                    "type": "number"
                },
                "practice_count": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Word Flashcard API",
	Description:      "Flashcards help you learn more vocabulary anytime, anywhere.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
